import type { Metadata } from "next";
import "./globals.css";
import { Provider as JotaiProvider } from "jotai";
import { AuthProvider } from "~/providers/Auth.provider";
import { Navbar } from "~/components/Navbar";
import { Sidebar } from "~/components/Sidebar";
import { Open_Sans } from "next/font/google";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: {
		icon: "/icon.svg",
	},
};

const openSans = Open_Sans({
	display: "swap",
	subsets: ["latin"],
	preload: true,
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased ${openSans.className} scroll-smooth overflow-x-hidden max-w-screen-2xl`}>
				<JotaiProvider>
					<AuthProvider>
						<Navbar />
						<div className="grid grid-cols-5 relative">
							<Sidebar />
							<main className="col-span-4 py-12 h-[300vh] px-8">{children}</main>
						</div>
					</AuthProvider>
				</JotaiProvider>
			</body>
		</html>
	);
}
